# Generated by Django 5.0.3 on 2024-04-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateTimeField(auto_now_add=True, verbose_name='Время платежа')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Сумма платежа')),
                ('status', models.BooleanField(default=False, verbose_name='Статус платежа')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='collect.collect', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
