# Generated by Django 5.0.3 on 2024-04-04 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название сбора')),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'День рожденья'), (1, 'Свадьба'), (2, 'Стартап')], verbose_name='Причина сбора')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание сбора')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000, message='Сумма не может превышать 100 млн руб')], verbose_name='Сумма сбора')),
                ('amount_now', models.PositiveIntegerField(default=0, verbose_name='Сумма на данный момент')),
                ('count_people', models.PositiveIntegerField(default=0, verbose_name='Количество людей сделавших пожертвований')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collect/', verbose_name='обложка сбора')),
                ('end_of_event', models.DateTimeField(verbose_name='Конец сбора')),
            ],
            options={
                'verbose_name': 'Групповой сбор',
                'verbose_name_plural': 'Групповые сборы',
            },
        ),
    ]
