# Generated by Django 5.0.3 on 2024-04-02 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='donates',
        ),
        migrations.AddField(
            model_name='collect',
            name='donates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donates', to=settings.AUTH_USER_MODEL, verbose_name='Донатеры'),
        ),
    ]
