# Generated by Django 5.0.3 on 2024-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_alter_collect_reason'),
        ('payment', '0003_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='donates',
            field=models.ManyToManyField(blank=True, null=True, related_name='donates', to='payment.payment', verbose_name='Донатеры'),
        ),
    ]
